# Generated by Django 5.2.7 on 2025-10-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='categoria',
            field=models.CharField(blank=True, default='Escreva o nome da categoria', max_length=50),
        ),
    ]
